language: python
python:
  - "3.6.4"

sudo: false

install:
  # Install conda
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - conda config --set always_yes yes --set changeps1 no
  - conda update conda
  - conda info

  - conda env create --name gssurgo --file=requirements.txt
  - source activate gssurgo  
  - pip install -e .
  - conda list

script:
  - pytest -v --ignore=scratch
