language: python
python:
  - "3.6.4"

sudo: required
dist: trusty

addons:  
  apt:
    sources:      
      - sourceline: 'ppa:ubuntugis/ubuntugis-unstable'      
    packages:      
      - libgdal-dev      
      - python3-dev

before_install:
  - gdal-config --version
  - pip install --upgrade pip

install:
  - pip install -r requirements.txt
  - pip install -e .

script:
  - pytest -v --ignore=scratch
