language: python
python:
  - "3.6.4"

sudo: required
dist: trusty

addons:  
  apt:
    sources:      
      - sourceline: 'ppa:ubuntugis/ubuntugis-unstable'      
    packages:
      - libgdal-dev
      - python-gdal      
      - libproj-dev
      - gdal-bin

before_install:
  - sudo add-apt-repository ppa:ubuntugis/ubuntugis-unstable --yes
  - sudo apt-get --yes --force-yes update -qq
  - sudo apt-get install --yes udunits-bin libproj-dev libgeos-dev libgdal-dev libgdal1-dev libudunits2-dev
  - gdal-config --version
  - pip install --upgrade pip

install:
  - pip install -r requirements.txt
  - pip install -e .

script:
  - pytest -v --ignore=scratch
