name: gssurgo
channels:
- conda-forge
dependencies:
- python>=3.6.4
- anaconda
- pip
- pandas==0.24.2
- matplotlib==3.1.0
- gdal==3.0.1
- pip:    
  - geopandas==0.5.0
  - rasterio==1.0.24
  - pytest==4.6.2